In [11]:
import numpy as np
import pandas as pd

In [12]:
emp = pd.DataFrame({
    'epid' : [1, 2, 3, 4, 5],
    'name' : ['v', 'k', 'h', 't', 'y'],
    'dep' : ['HR', 'It', 'HPP', 'MNN', 'WEE']
})

asll = pd.DataFrame({
    'epid' : [1, 2, 3, 6, 7],
    'sal' : [45, 453, 4634, 56, 456],
    'bonus' : [44536, 6453, 436, 56, 67]
})

In [13]:
emp

   epid name  dep
0     1    v   HR
1     2    k   It
2     3    h  HPP
3     4    t  MNN
4     5    y  WEE

In [14]:
asll

   epid   sal  bonus
0     1    45  44536
1     2   453   6453
2     3  4634    436
3     6    56     56
4     7   456     67

In [15]:
pd.merge(emp, asll, on='epid')

   epid name  dep   sal  bonus
0     1    v   HR    45  44536
1     2    k   It   453   6453
2     3    h  HPP  4634    436

In [16]:
pd.merge(emp, asll, on='epid', how="outer")

   epid name  dep     sal    bonus
0     1    v   HR    45.0  44536.0
1     2    k   It   453.0   6453.0
2     3    h  HPP  4634.0    436.0
3     4    t  MNN     NaN      NaN
4     5    y  WEE     NaN      NaN
5     6  NaN  NaN    56.0     56.0
6     7  NaN  NaN   456.0     67.0

In [17]:
pd.merge(emp, asll, on='epid', how= "left")

   epid name  dep     sal    bonus
0     1    v   HR    45.0  44536.0
1     2    k   It   453.0   6453.0
2     3    h  HPP  4634.0    436.0
3     4    t  MNN     NaN      NaN
4     5    y  WEE     NaN      NaN

In [18]:
pd.merge(emp, asll, on='epid', how= "right")

   epid name  dep   sal  bonus
0     1    v   HR    45  44536
1     2    k   It   453   6453
2     3    h  HPP  4634    436
3     6  NaN  NaN    56     56
4     7  NaN  NaN   456     67