In [4]:
import numpy as np
import pandas as pd

In [12]:
data = {
    'A' : [1, 2, 3, 4, 5],
    'B' : [1, 2, 3, 4, 5],
    'C' : [1, 2, 3, np.nan, np.nan],
    'D' : [1, np.nan, np.nan, np.nan, 5]
    
}
df = pd.DataFrame(data)

In [13]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [14]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2  False  False  False   True
3  False  False   True   True
4  False  False   True  False

In [8]:
df.isna().sum()

A    1
B    1
C    2
D    3
dtype: int64

In [ ]:
# Finding Removing and Filling Missing Data

In [15]:
df.dropna()

   A  B    C    D
0  1  1  1.0  1.0

In [18]:
df.dropna(thresh=4)

   A  B    C    D
0  1  1  1.0  1.0

In [19]:
df

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  NaN
2  3  3  3.0  NaN
3  4  4  NaN  NaN
4  5  5  NaN  5.0

In [20]:
df.fillna(0)

   A  B    C    D
0  1  1  1.0  1.0
1  2  2  2.0  0.0
2  3  3  3.0  0.0
3  4  4  0.0  0.0
4  5  5  0.0  5.0

In [21]:
val= {'A': 0, 'B': 9, 'C': 89, 'D': 45}
df.fillna(value=val)

   A  B     C     D
0  1  1   1.0   1.0
1  2  2   2.0  45.0
2  3  3   3.0  45.0
3  4  4  89.0  45.0
4  5  5  89.0   5.0