In [88]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt 
import warnings
warnings.filterwarnings('ignore')

In [89]:
df = sns.load_dataset('titanic')

In [90]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,Second,man,True,NaN,Southampton,no,True
887,1,1,female,19.0,0,0,30.0000,S,First,woman,False,B,Southampton,yes,True
888,0,3,female,NaN,1,2,23.4500,S,Third,woman,False,NaN,Southampton,no,False
889,1,1,male,26.0,0,0,30.0000,C,First,man,True,C,Cherbourg,yes,True
890,0,3,male,32.0,0,0,7.7500,Q,Third,man,True,NaN,Queenstown,no,True

In [91]:
df[(df['adult_male'] == False) & (df['sex'] == 'male')]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
7,0,3,male,2.00,3,1,21.0750,S,Third,child,False,NaN,Southampton,no,False
16,0,3,male,2.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
50,0,3,male,7.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
59,0,3,male,11.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
63,0,3,male,4.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
78,1,2,male,0.83,0,2,29.0000,S,Second,child,False,NaN,Southampton,yes,False
125,1,3,male,12.00,1,0,11.2417,C,Third,child,False,NaN,Cherbourg,yes,False
164,0,3,male,1.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
165,1,3,male,9.00,0,2,20.5250,S,Third,child,False,NaN,Southampton,yes,False
171,0,3,male,4.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
182,0,3,male,9.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,no,False
183,1,2,male,1.00,2,1,39.0000,S,Second,child,False,F,Southampton,yes,False
193,1,2,male,3.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
261,1,3,male,3.00,4,2,31.3875,S,Third,child,False,NaN,Southampton,yes,False
278,0,3,male,7.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
305,1,1,male,0.92,1,2,151.5500,S,First,child,False,C,Southampton,yes,False
340,1,2,male,2.00,1,1,26.0000,S,Second,child,False,F,Southampton,yes,False
348,1,3,male,3.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
352,0,3,male,15.00,1,1,7.2292,C,Third,child,False,NaN,Cherbourg,no,False
386,0,3,male,1.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
407,1,2,male,3.00,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
445,1,1,male,4.00,0,2,81.8583,S,First,child,False,A,Southampton,yes,False
480,0,3,male,9.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
489,1,3,male,9.00,1,1,15.9000,S,Third,child,False,NaN,Southampton,yes,False
549,1,2,male,8.00,1,1,36.7500,S,Second,child,False,NaN,Southampton,yes,False
683,0,3,male,14.00,5,2,46.9000,S,Third,child,False,NaN,Southampton,no,False
686,0,3,male,14.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
731,0,3,male,11.00,0,0,18.7875,C,Third,child,False,NaN,Cherbourg,no,True
751,1,3,male,6.00,0,1,12.4750,S,Third,child,False,E,Southampton,yes,False
755,1,2,male,0.67,1,1,14.5000,S,Second,child,False,NaN,Southampton,yes,False
787,0,3,male,8.00,4,1,29.1250,Q,Third,child,False,NaN,Queenstown,no,False
788,1,3,male,1.00,1,2,20.5750,S,Third,child,False,NaN,Southampton,yes,False
802,1,1,male,11.00,1,2,120.0000,S,First,child,False,B,Southampton,yes,False
803,1,3,male,0.42,0,1,8.5167,C,Third,child,False,NaN,Cherbourg,yes,False
819,0,3,male,10.00,3,2,27.9000,S,Third,child,False,NaN,Southampton,no,False
824,0,3,male,2.00,4,1,39.6875,S,Third,child,False,NaN,Southampton,no,False
827,1,2,male,1.00,0,2,37.0042,C,Second,child,False,NaN,Cherbourg,yes,False
831,1,2,male,0.83,1,1,18.7500,S,Second,child,False,NaN,Southampton,yes,False
850,0,3,male,4.00,4,2,31.2750,S,Third,child,False,NaN,Southampton,no,False
869,1,3,male,4.00,1,1,11.1333,S,Third,child,False,NaN,Southampton,yes,False

In [92]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [93]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [94]:
df.drop(['class','deck', 'embark_town',
       'alive', 'alone', 'who'], axis=1, inplace=True)

In [95]:
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male
0,0,3,male,22.0,1,0,7.2500,S,True
1,1,1,female,38.0,1,0,71.2833,C,False
2,1,3,female,26.0,0,0,7.9250,S,False
3,1,1,female,35.0,1,0,53.1000,S,False
4,0,3,male,35.0,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.0,0,0,13.0000,S,True
887,1,1,female,19.0,0,0,30.0000,S,False
888,0,3,female,NaN,1,2,23.4500,S,False
889,1,1,male,26.0,0,0,30.0000,C,True
890,0,3,male,32.0,0,0,7.7500,Q,True

In [96]:
df["age"].fillna(df['age'].mean(), inplace=True)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male
0,0,3,male,22.000000,1,0,7.2500,S,True
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,False
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,False
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [97]:
df.dropna(subset=["embarked"], inplace= True)
df

,survived,pclass,sex,age,sibsp,parch,fare,embarked,adult_male
0,0,3,male,22.000000,1,0,7.2500,S,True
1,1,1,female,38.000000,1,0,71.2833,C,False
2,1,3,female,26.000000,0,0,7.9250,S,False
3,1,1,female,35.000000,1,0,53.1000,S,False
4,0,3,male,35.000000,0,0,8.0500,S,True
...,...,...,...,...,...,...,...,...,...
886,0,2,male,27.000000,0,0,13.0000,S,True
887,1,1,female,19.000000,0,0,30.0000,S,False
888,0,3,female,29.699118,1,2,23.4500,S,False
889,1,1,male,26.000000,0,0,30.0000,C,True
890,0,3,male,32.000000,0,0,7.7500,Q,True

In [98]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 9 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   survived    889 non-null    int64
 1   pclass      889 non-null    int64
 2   sex         889 non-null    object
 3   age         889 non-null    float64
 4   sibsp       889 non-null    int64
 5   parch       889 non-null    int64
 6   fare        889 non-null    float64
 7   embarked    889 non-null    object
 8   adult_male  889 non-null    bool
dtypes: bool(1), float64(2), int64(4), object(2)
memory usage: 63.4+ KB

In [99]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
le = LabelEncoder()

In [100]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  adult_male
0         0       3    male  22.0      1      0   7.2500        S        True
1         1       1  female  38.0      1      0  71.2833        C       False
2         1       3  female  26.0      0      0   7.9250        S       False
3         1       1  female  35.0      1      0  53.1000        S       False
4         0       3    male  35.0      0      0   8.0500        S        True

In [101]:
df['sex'] = le.fit_transform(df["sex"])

In [102]:
df = pd.get_dummies(df, columns = ['embarked'])

In [103]:
df.astype(int)

,survived,pclass,sex,age,sibsp,parch,fare,adult_male,embarked_C,embarked_Q,embarked_S
0,0,3,1,22,1,0,7,1,0,0,1
1,1,1,0,38,1,0,71,0,1,0,0
2,1,3,0,26,0,0,7,0,0,0,1
3,1,1,0,35,1,0,53,0,0,0,1
4,0,3,1,35,0,0,8,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,1,27,0,0,13,1,0,0,1
887,1,1,0,19,0,0,30,0,0,0,1
888,0,3,0,29,1,2,23,0,0,0,1
889,1,1,1,26,0,0,30,1,1,0,0
890,0,3,1,32,0,0,7,1,0,1,0

In [104]:
X = df.drop(columns = ['survived'])
y = df['survived']

In [106]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

In [109]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression()

In [110]:
model.fit(X_train, y_train)

LogisticRegression()

In [113]:
y_pred = model.predict(X_test)

In [114]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_pred)
r2

0.19531977130700717

In [115]:
n = X_test.shape[0]
p = X_test.shape[1]
adjusted_r2 = 1 - ((1-r2)*(n-1)/(n-p-1))
adjusted_r2

0.14713532647509142