In [22]:
import pandas as pd

In [23]:
data = {
    'Name' : ['Vruti', 'Krishna', 'Urvashi', 'Lendaa'],
    'Age' : [ 34, 33, 64, 56],
    'City' : ['suradwt', 'dwfwhj', 'ewgrwg', 'ewfre']
    }
pd.DataFrame(data)

      Name  Age     City
0    Vruti   34  suradwt
1  Krishna   33   dwfwhj
2  Urvashi   64   ewgrwg
3   Lendaa   56    ewfre

In [24]:
data["wish"] = ["Nothing", "Lambo", "Boyfriend", "idk"]

In [25]:
pd.DataFrame(data)

      Name  Age     City       wish
0    Vruti   34  suradwt    Nothing
1  Krishna   33   dwfwhj      Lambo
2  Urvashi   64   ewgrwg  Boyfriend
3   Lendaa   56    ewfre        idk

In [26]:
dff = pd.DataFrame(data)
print(dff)

      Name  Age     City       wish
0    Vruti   34  suradwt    Nothing
1  Krishna   33   dwfwhj      Lambo
2  Urvashi   64   ewgrwg  Boyfriend
3   Lendaa   56    ewfre        idk

In [27]:
print(dff.loc[[2,3]]["City"])

2    ewgrwg
3     ewfre
Name: City, dtype: object

In [28]:
dff.drop('wish', axis = 1)

      Name  Age     City
0    Vruti   34  suradwt
1  Krishna   33   dwfwhj
2  Urvashi   64   ewgrwg
3   Lendaa   56    ewfre

In [32]:
dff[(dff["Age"]> 60) & (dff["Name"] == 'Urvashi')]

      Name  Age    City       wish
2  Urvashi   64  ewgrwg  Boyfriend